name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.13.1
            otp: 24.2

    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.hex
          ~/.mix
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Compile Deps
      run: mix deps.compile
    - name: Compile
      run: mix compile --warnings-as-errors
    - name: Formatting
      run: MIX_ENV=test mix format --check-formatted
    - name: Run Tests
      run: mix test
